name: Helm Chart Tests

on:
    pull_request:
      branches: [main]

jobs:
  lint_and_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add Bitnami dependencies
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: update bitnami
        run: helm repo update

      - name: Install Helm dependencies
        run: helm dependency build .

      - name: Lint Helm chart
        run: helm lint .

      - name: Template Helm chart
        run: helm template .

